version: '3'
services:
    mysql:
        image: mysql:latest
        container_name: cmysql
        environment: 
            - MYSQL_ROOT_PASSWORD=12345
            - MYSQL_DATABASE=devops
        networks: 
            - minha-rede
        ports:
            - "3307:3306"

    devops1:
        image: openjdk:8
        container_name: cdevops1
        ports:
            - "8081:8080"
        networks: 
            - minha-rede
        depends_on:
            - "mysql"
        volumes:
            - ./Devops1/target:/usr/src/app
        environment:
            - DATABASE_HOST=mysql
            - DATABASE_PORT=3306
            - DATABASE_USER=root
            - DATABASE_PASS=12345
        working_dir: /usr/src/app
        entrypoint: "java -jar Devops1-0.0.2-SNAPSHOT.jar Application"

networks: 
    minha-rede:
        driver: bridge