version: '3'
services:
    # maven1:
    #     image: maven:latest
    #     container_name: cmaven1
    #     networks: 
    #         - minha-rede
    #     volumes:
    #         - .:/usr/src/output
    #         - ./Devops1:/usr/src/mymaven
    #     working_dir: /usr/src/mymaven
    #     entrypoint: "mvn package -Dmaven.test.skip=true"
    # maven2:
    #     image: maven:latest
    #     container_name: cmaven2
    #     networks: 
    #         - minha-rede
    #     volumes:
    #         - .:/usr/src/output
    #         - ./Devops2:/usr/src/mymaven
    #     working_dir: /usr/src/mymaven
    #     entrypoint: "mvn package -Dmaven.test.skip=true"

    mysql:
        image: mysql:latest
        container_name: cmysql
        environment: 
            - MYSQL_ROOT_PASSWORD=12345
            - MYSQL_DATABASE=devops
        networks: 
            - minha-rede
        ports:
            - "3307:3306"

    devops1:
        image: openjdk:8
        container_name: cdevops1
        ports:
            - "8081:8080"
            - "3306"
        networks: 
            - minha-rede
        depends_on:
            - "mysql"
#            - "maven1"
        volumes:
            - .:/usr/src/app
        environment:
            - DATABASE_HOST=mysql
            - DATABASE_PORT=3306
            - DATABASE_USER=root
            - DATABASE_PASS=12345
            - DATABASE_SCHEMA=devops
        working_dir: /usr/src/app
        entrypoint: "java -jar Devops1.jar Application"

    devops2:
        image: openjdk:8
        container_name: cdevops2
        ports:
            - "8082:8080"
            - "3306"
        networks: 
            - minha-rede
        depends_on:
            - "mysql"
#            - "maven2"
        volumes:
            - .:/usr/src/app
        environment:
            - DATABASE_HOST=mysql
            - DATABASE_PORT=3306
            - DATABASE_USER=root
            - DATABASE_PASS=12345
            - DATABASE_SCHEMA=devops
        working_dir: /usr/src/app
        entrypoint: "java -jar Devops2.jar Application"

networks: 
    minha-rede:
        driver: bridge
